# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  ###### ipadic ######

  - package-ecosystem: "docker"
    directory: "ipadic/alpine3.19"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: [version-update:semver-major, version-update:semver-minor]

  - package-ecosystem: "docker"
    directory: "ipadic/alpine3.18"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: [version-update:semver-major, version-update:semver-minor]

  - package-ecosystem: "docker"
    directory: "ipadic/alpine3.17"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: [version-update:semver-major, version-update:semver-minor]

  - package-ecosystem: "docker"
    directory: "ipadic/alpine3.16"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: [version-update:semver-major, version-update:semver-minor]

  - package-ecosystem: "docker"
    directory: "ipadic/bookworm"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "ipadic/bullseye"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "ipadic/buster"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "ipadic/slim-bookworm"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "ipadic/slim-bullseye"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "ipadic/slim-buster"
    schedule:
      interval: "daily"

  ###### jumandic ######

  - package-ecosystem: "docker"
    directory: "jumandic/alpine3.19"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: [version-update:semver-major, version-update:semver-minor]

  - package-ecosystem: "docker"
    directory: "jumandic/alpine3.18"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: [version-update:semver-major, version-update:semver-minor]

  - package-ecosystem: "docker"
    directory: "jumandic/alpine3.17"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: [version-update:semver-major, version-update:semver-minor]

  - package-ecosystem: "docker"
    directory: "jumandic/alpine3.16"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: [version-update:semver-major, version-update:semver-minor]

  - package-ecosystem: "docker"
    directory: "jumandic/bookworm"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "jumandic/bullseye"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "jumandic/buster"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "jumandic/slim-bookworm"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "jumandic/slim-bullseye"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "jumandic/slim-buster"
    schedule:
      interval: "daily"
