# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain docker base images
  - package-ecosystem: "docker"
    directories:
      - "ipadic/alpine3.19"
      - "ipadic/alpine3.18"
      - "ipadic/alpine3.17"
      - "ipadic/alpine3.16"
      - "ipadic/bookworm"
      - "ipadic/bullseye"
      - "ipadic/buster"
      - "ipadic/slim-bookworm"
      - "ipadic/slim-bullseye"
      - "ipadic/slim-buster"
      - "jumandic/alpine3.19"
      - "jumandic/alpine3.18"
      - "jumandic/alpine3.17"
      - "jumandic/alpine3.16"
      - "jumandic/bookworm"
      - "jumandic/bullseye"
      - "jumandic/buster"
      - "jumandic/slim-bookworm"
      - "jumandic/slim-bullseye"
      - "jumandic/slim-buster"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: [version-update:semver-major, version-update:semver-minor]
