name: Build Docker Images

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - alpine3.11
          - alpine3.12
          - alpine3.13
          - alpine3.14
          - buster
          - slim-buster
        dictionary:
          - ipadic
          - jumandic
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker buildx build --pull --platform linux/amd64,linux/arm64 .
        working-directory: ${{ matrix.dictionary }}/${{ matrix.distribution }}

      - name: Publish to DockerHub
        run: |
          printenv PASSWORD | docker login --username "$USERNAME" --password-stdin
          docker buildx build --push --platform linux/amd64,linux/arm64 -t "$USERNAME/mecab:${{ matrix.dictionary }}-${{ matrix.distribution }}" .
          docker logout
        working-directory: ${{ matrix.dictionary }}/${{ matrix.distribution }}
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Publish to GitHub Packages Container registry
        run:
          printenv PASSWORD | docker login ghcr.io --username "$USERNAME" --password-stdin
          docker buildx build --push --platform linux/amd64,linux/arm64 -t ghcr.io/$USERNAME/mecab:${{ matrix.dictionary }}-${{ matrix.distribution }} .
          docker logout
        env:
          USERNAME: ${{ github.repository_owner }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
