name: Build Docker Images

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - alpine3.11
          - alpine3.12
          - alpine3.13
          - alpine3.14
          - buster
          - slim-buster
        dictionary:
          - ipadic
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 .
        working-directory: ${{ matrix.dictionary }}/${{ matrix.distribution }}

      - name: Login to DockerHub
        run:
          printenv PASSWORD | docker login --username "$USERNAME"
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Publish
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/mecab:${{ matrix.dictionary }}-${{ matrix.distribution }} .
        working-directory: ${{ matrix.dictionary }}/${{ matrix.distribution }}
