name: Build Docker Images

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - alpine3.11
          - alpine3.12
          - alpine3.13
          - alpine3.14
          - buster
          - slim-buster
        dict:
          - ipadic
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker buildx build --load --platform linux/amd64,linux/arm64 -t mecab .
