name: Build jumandic/slim-buster

on:
  push:
    branches:
      - main
    tags:
      - "jumandic-slim-buster/*"
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.38"
      - run: |
          ./scripts/build.sh jumandic slim-buster
