name: Build jumandic-buster

on:
  push:
    branches:
      - main
    tags:
      - "jumandic-buster/*"
  pull_request:
    paths:
      - ".github/workflows/jumandic-buster.yml"
      - "jumandic/buster/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.38"
      - run: |
          ./scripts/build.pl jumandic buster

      - name: Publish to DockerHub
        env:
          USERNAME: ${{ vars.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          printenv PASSWORD | docker login --username "$USERNAME" --password-stdin
          ./scripts/publish.pl jumandic buster "$USERNAME"
          docker logout

      - name: Publish to GitHub Packages Container registry
        env:
          USERNAME: ${{ github.repository_owner }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          printenv PASSWORD | docker login --username "$USERNAME" --password-stdin ghcr.io
          ./scripts/publish.pl jumandic buster ghcr.io/"$USERNAME"
          docker logout

      - name: Configure AWS Credentials
        uses: fuller-inc/actions-aws-assume-role@v1
        continue-on-error: true
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::445285296882:role/mecab-ecr-DeploymentRole-HLLU42OOK2YJ
          role-session-tagging: true
      - name: Publish to ECR Public Registry
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/shogo82148
          ./scripts/publish.pl jumandic buster public.ecr.aws/shogo82148
          docker logout
